# Generated by Django 3.2.8 on 2021-12-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_coupon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
